package:
  name: scikit-learn
  version: "0.18.dev0"

source:
  path: ../sklearn-dev

requirements:
  build:
    - python
    - setuptools
    - pip
    - wheel
    - mkl
    - numpy
    - scipy
    - cython
